### ISSUE TITLE
Slideshow (under Catalog) doesn't work

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#166] opened 2015-09-08 14:49 UTC
Link to this example: http://sufia-stage.northwestern.edu/catalog?page=2&view=slideshow

Please see relevant image and link below where you can see that the last option "Slideshow" doesn't work properly. The other options: "List", "Gallery", "Masonry" work.

<img width="1248" alt="screen shot 2015-09-06 at 10 38 26 pm" src="https://cloud.githubusercontent.com/assets/3239996/9737850/3a8e8f16-560e-11e5-8401-d5bd4f0d763d.png">

**The look needs to change since one cannot tell what's the text in the grey text box.**

**Comment by phebal** [comment] 2015-09-11 12:49
Duplicate of #66

**Closed by phebal** 2015-09-11 12:49 UTC
