### ISSUE TITLE
Make historical views, downloads, and Altmetric donut available for DigitalHub content

### ISSUE THREAD

**Issue by carsonicator** [galterlibrary/digital-repository#883] opened 2021-06-18 15:23 UTC
We need to retain views, downloads, and Altmetric donuts for deposited records in DigitalHub and make this available to users after we transition to Prism. We can discuss the details, but we would expect something like the following:

1. A user goes to a webpage to find metrics for records they deposited in DigitalHub.
2. The user enters the DOI of the record.
3. Data on this record is returned, including views, downloads, Altmetric donut, and start / end dates of the gathered statistics.

**Comment by sharpattack** [comment] 2022-09-30 14:52
Duplicate of https://github.com/galterlibrary/digitalhub-2/issues/53

**Closed by sharpattack** 2022-09-30 14:52 UTC
